---
fixtures:
  forge_modules:
    apt: 'puppetlabs-apt'
    archive: 'puppet-archive'
    augeas_core: 'puppetlabs-augeas_core'
    chocolatey: 'puppetlabs-chocolatey'
    concat: 'puppetlabs-concat'
    cron_core: 'puppetlabs-cron_core'
    epel: 'puppet-epel'
    git: 'puppetlabs-git'
    homebrew: 'thekevjames-homebrew'
    logrotate: 'puppet-logrotate'
    mount_core: 'puppetlabs-mount_core'
    ntp: 'puppetlabs-ntp'
    openvmtools: 'puppet-openvmtools'
    pkgng: 'zleslie-pkgng'
    powershell: 'puppetlabs-powershell'
    puppet_agent: 'puppetlabs-puppet_agent'
    registry: 'puppetlabs-registry'
    rsync: 'puppetlabs-rsync'
    selinux: 'puppet-selinux'
    sshkeys_core: 'puppetlabs-sshkeys_core'
    stdlib: 'puppetlabs-stdlib'
    wget: 'puppet-wget'
    yum: 'puppet-yum'
  symlinks:
    osbaseline: "#{File.dirname(source_dir)}/puppet-osbaseline"
...
